# Project:   dfe-docker
# File:      config/transform-vector/kafka.yaml
# Purpose:   dfe-transform-vector config - Kafka transport (used by the Kafka profiles)
# Language:  YAML
#
# License:   BUSL-1.1
# Copyright: (c) 2026 HYPERI PTY LIMITED

dfe_source: main
source:
  brokers: [kafka:9092]
sink:
  brokers: [kafka:9092]