# Project:   dfe-docker
# File:      config/loader/kafka-load.yaml
# Purpose:   dfe-loader config - Kafka consumer of the transform _load topic (used by transform profiles)
# Language:  YAML
#
# License:   BUSL-1.1
# Copyright: (c) 2026 HYPERI PTY LIMITED

clickhouse:
  hosts:
    - clickhouse:8123
  database: dfe
  protocol: http
  username: env:CLICKHOUSE_USERNAME
  password: env:CLICKHOUSE_PASSWORD

kafka:
  brokers:
    - kafka:9092
  group: dfe-loader
  topics:
    - main_load