#!/usr/bin/env python3
#  Project:      dfe-docker
#  File:         scripts/container_prefix.py
#  Purpose:      Re-prefix every container name so a second stack can share a daemon
#  Language:     Python
#
#  License:      BUSL-1.1
#  Copyright:    (c) 2026 HYPERI PTY LIMITED

"""One generated fragment that puts DFE_CONTAINER_PREFIX in front of every container name.

``container_name`` is daemon-wide, so two stacks from this compose file collide on
every name however their project names and ports differ. A prefix set in .env or
the environment is written into ``docker-compose.prefix.yml``, which ``make``
chains after the per-source instance fragment, so an instance's container is
renamed with the rest.

The prefix is also what a test harness joins to a service name to reach its
container, and the fluentd log tag is the container name, so a prefixed stack's
logs land under the prefixed names.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

from _common import COMPOSE_FILE, REPO_ROOT, _print

PREFIX_ENV_VAR = "DFE_CONTAINER_PREFIX"
COMPOSE_PREFIX_FILE = REPO_ROOT / "docker-compose.prefix.yml"

# Docker's own container-name rule, less the first character a prefix may not
# end a name with: a prefix is followed by the committed name.
_VALID_PREFIX = re.compile(r"[a-zA-Z0-9][a-zA-Z0-9_.-]*")
_SERVICE_LINE = re.compile(r"^  ([a-zA-Z0-9][a-zA-Z0-9_.-]*):\s*$")
_NAME_LINE = re.compile(r"^    container_name:\s*(\S+)\s*$")

HEADER = (
    "# Generated by scripts/container_prefix.py, which `make` runs with the profile.\n"
    f"# {PREFIX_ENV_VAR} in front of every container name. Not committed: regenerated\n"
    "# on every run, and removed when the prefix is empty.\n"
)


class PrefixError(ValueError):
    """Raised when the prefix cannot start a container name."""


def validate(prefix: str) -> str:
    """Return the prefix, or raise when Docker would refuse the names it makes."""
    if prefix and not _VALID_PREFIX.fullmatch(prefix):
        raise PrefixError(
            f"{PREFIX_ENV_VAR}={prefix!r} cannot start a container name: use letters, "
            "digits, '_', '.' or '-', starting with a letter or a digit"
        )
    return prefix


def committed_names(*, compose_file: Path | None = None) -> dict[str, str]:
    """Every service in the compose file that fixes its container name, and the name.

    A line reader rather than a YAML parse, for the reason the rest of the helpers
    give: they run with no PyYAML. The file's layout is two-space services with
    their keys four in.
    """
    names: dict[str, str] = {}
    in_services = False
    current = ""
    text = (compose_file or COMPOSE_FILE).read_text(encoding="utf-8")
    for line in text.splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        if not line.startswith(" "):
            in_services = line.rstrip() == "services:"
            current = ""
            continue
        if not in_services:
            continue
        service = _SERVICE_LINE.match(line)
        if service:
            current = service.group(1)
            continue
        name = _NAME_LINE.match(line)
        if name and current:
            names[current] = name.group(1).strip("\"'")
    return names


def fragment(prefix: str, names: dict[str, str]) -> str:
    """The fragment renaming each container, in service order."""
    lines = [HEADER.rstrip("\n"), "services:"]
    for service in sorted(names):
        lines += [f"  {service}:", f"    container_name: {prefix}{names[service]}"]
    return "\n".join(lines) + "\n"


def write(prefix: str, instance_names: list[str], *, path: Path | None = None) -> bool:
    """Write the fragment, or remove it when there is no prefix.

    ``instance_names`` are the generated per-source services, whose container name
    is their service name. Returns whether a fragment is in place.
    """
    target = path or COMPOSE_PREFIX_FILE
    if not validate(prefix):
        target.unlink(missing_ok=True)
        return False
    names = committed_names()
    names.update({name: name for name in instance_names})
    content = fragment(prefix, names)
    if not target.is_file() or target.read_text(encoding="utf-8") != content:
        target.write_text(content, encoding="utf-8", newline="\n")
    return True


def main() -> int:
    for service, name in sorted(committed_names().items()):
        print(f"{service}\t{name}")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except PrefixError as error:
        _print(msg=str(error))
        sys.exit(1)
