#!/usr/bin/env python3
#  Project:      dfe-docker
#  File:         scripts/instances.py
#  Purpose:      Declare one container per source for the apps that run one each
#  Language:     Python
#
#  License:      BUSL-1.1
#  Copyright:    (c) 2026 HYPERI PTY LIMITED

"""One Compose service per app instance, from the index dfe-engine writes.

Some apps run one deployment per SOURCE rather than one for the stack -- the
fetcher polls one upstream, each transform runs one source's programs. On
Kubernetes the layer2-apps ApplicationSet globs the engine's values overlays and
fans out one Application per file. Compose has no such generator: it declares its
services in a committed file and creates none at run time, so the count had to be
hardcoded and a deployment ran exactly one fetcher however many sources it had.

This is that generator. dfe-engine renders each instance's config into its own
directory and writes the names to ``env/<service>.instances``; the fragment here
turns each name into a service that ``extends`` the app's committed one, so the
image, volumes, limits and healthcheck have a single definition and only what
must differ per instance is written out.

A deployment with no source of a given kind has an empty index and gets no
service, which is how a fresh stack starts with none of these apps running.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from _common import (
    COMPOSE_FILE,
    ENV_DIR,
    REPO_ROOT,
    SERVICE_CONFIG_FILE,
    _print,
    _rel_path,
)

COMPOSE_INSTANCES_FILE = REPO_ROOT / "docker-compose.instances.yml"

INDEX_SUFFIX = ".instances"
"""What dfe-engine names its index (appmgmt/appconfig.py INSTANCE_INDEX_SUFFIX)."""

CUSTOM_ENV_SUFFIX = ".custom.env"
"""What dfe-engine names a service's custom env file (appmgmt/appconfig.py)."""

# Where the apps mount the volume dfe-engine renders into. The engine is handed
# the same path as DFE_APP_CONFIG_MOUNT, so the two cannot disagree.
APP_CONFIG_MOUNT = "/etc/dfe/apps"

# `extends` does not carry depends_on, so each generated service declares its
# own. These are the gates every per-source app shares: the engine writes the
# config it reads and creates its topics, and dlq-init prepares the dead-letter
# queue it produces to. All optional, for the tiers that run none of them.
INSTANCE_DEPENDS_ON = (
    ("dfe-engine", "service_healthy"),
    ("dlq-init", "service_completed_successfully"),
)

HEADER = (
    "# Generated by scripts/instances.py, which `make` runs with the profile.\n"
    "# One service per app instance, from the env/<app>.instances index dfe-engine\n"
    "# writes when it renders that instance's config. Not committed: regenerated\n"
    "# on every run, and removed when the deployment has no such instance.\n"
)


def index_file(service: str, *, env_dir: Path | None = None) -> Path:
    """Where dfe-engine records the instances of one app."""
    return (env_dir or ENV_DIR) / f"{service}{INDEX_SUFFIX}"


def read_index(path: Path) -> list[str]:
    """The instance names in one index, in the order the engine wrote them."""
    if not path.is_file():
        return []
    return [
        line.strip()
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip()
    ]


def declared(*, env_dir: Path | None = None) -> dict[str, list[str]]:
    """Every app with an index here, and the instances it names.

    Discovered rather than listed: which apps run one deployment per source is
    dfe-infra apps.yaml's to say, and the engine renders for exactly those, so a
    new one joins by appearing here.
    """
    found: dict[str, list[str]] = {}
    directory = env_dir or ENV_DIR
    if not directory.is_dir():
        return found
    for path in sorted(directory.glob(f"*{INDEX_SUFFIX}")):
        service = path.name[: -len(INDEX_SUFFIX)]
        names = read_index(path)
        if names:
            found[service] = names
    return found


def service_name(service: str, instance: str) -> str:
    """What the instance's container is called, matching the engine's own hint."""
    return f"{service}-{instance}"


def custom_env_file(name: str) -> str:
    """The env file dfe-engine writes one compose service's custom keys to.

    Keyed on the service name, so each instance has its own
    (appmgmt/appconfig.py CUSTOM_ENV_SUFFIX).
    """
    return f"env/{name}{CUSTOM_ENV_SUFFIX}"


def _service_block(service: str, instance: str, compose_file: str) -> list[str]:
    """One generated service: what differs from the app's committed definition.

    Ports are dropped rather than offset. The app publishes an operator port and
    an ingest listener, and N instances cannot share one host port; on Kubernetes
    this app renders no Service either, so nothing outside the stack addresses an
    instance directly.

    The instance's own custom env file is appended to the ones `extends` carries,
    so its keys win over the app's.
    """
    name = service_name(service, instance)
    config = f"{APP_CONFIG_MOUNT}/{service}/{instance}/{SERVICE_CONFIG_FILE[service]}"
    lines = [
        f"  {name}:",
        "    extends:",
        f"      file: {compose_file}",
        f"      service: {service}",
        f"    container_name: {name}",
        f'    command: ["--config", "{config}"]',
        "    env_file:",
        f"      - path: {custom_env_file(name)}",
        "        required: false",
        "    environment:",
        f"      OTEL_SERVICE_NAME: {name}",
        "    ports: !reset []",
        "    depends_on:",
    ]
    for dependency, condition in INSTANCE_DEPENDS_ON:
        lines += [
            f"      {dependency}:",
            f"        condition: {condition}",
            "        required: false",
        ]
    lines.append("")
    return lines


def fragment(
    instances: dict[str, list[str]], *, compose_file: str = "docker-compose.yml"
) -> str:
    """The whole compose fragment for the instances given."""
    lines = [HEADER.rstrip("\n"), "services:"]
    for service in sorted(instances):
        for instance in instances[service]:
            lines += _service_block(service, instance, compose_file)
    return "\n".join(lines).rstrip("\n") + "\n"


def services(instances: dict[str, list[str]]) -> list[str]:
    """Every generated service name, in the order the fragment declares them."""
    return [
        service_name(service, instance)
        for service in sorted(instances)
        for instance in instances[service]
    ]


def extendable(service: str, *, compose_file: Path | None = None) -> bool:
    """Whether this repo declares the committed service an instance extends.

    An ``extends`` naming a service that is not there fails the whole compose
    file, so an app that has no committed definition is reported by name rather
    than written into the fragment.
    """
    if service not in SERVICE_CONFIG_FILE:
        return False
    text = (compose_file or COMPOSE_FILE).read_text(encoding="utf-8")
    return f"\n  {service}:\n" in text


def unknown_apps(
    instances: dict[str, list[str]], *, compose_file: Path | None = None
) -> list[str]:
    """Apps an index names that this repo declares no compose service for."""
    return sorted(s for s in instances if not extendable(s, compose_file=compose_file))


def write(instances: dict[str, list[str]], *, path: Path | None = None) -> bool:
    """Write the fragment, or remove it when the deployment has no instance.

    Returns whether a fragment is in place, which is what decides whether the
    Makefile chains it. Removed rather than left empty: a stale file would
    declare containers for sources this deployment no longer has.
    """
    target = path or COMPOSE_INSTANCES_FILE
    if not instances:
        target.unlink(missing_ok=True)
        return False
    content = fragment(instances, compose_file=COMPOSE_FILE.name)
    if not target.is_file() or target.read_text(encoding="utf-8") != content:
        target.write_text(content, encoding="utf-8", newline="\n")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(
        prog="instances.py", description=__doc__.split("\n")[0].strip()
    )
    parser.add_argument(
        "--list",
        action="store_true",
        help="print the service names one per line and write nothing",
    )
    args = parser.parse_args()

    found = declared()
    unknown = unknown_apps(found)
    if unknown:
        _print(
            msg=f"dfe-engine named instances of {', '.join(unknown)}, which this repo "
            "declares no compose service for -- add one, or the sources bound to it "
            "are stored and never run"
        )
        return 1
    if args.list:
        for name in services(found):
            print(name)
        return 0
    if write(found):
        _print(
            msg=f"{_rel_path(path=COMPOSE_INSTANCES_FILE)}: {len(services(found))} "
            f"instance service(s) -- {', '.join(services(found))}"
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())
